# The NumPy array object

## What are NumPy and NumPy arrays?

* High-level number objects: integers and floating point
* Containers: lists (costless insertion and append)

* Numpy provides extension package to Python for multi-dimensional arrays
* Closer to hardware (efficiency)
* Designed for scientific computation (convenience)
* Also known as array oriented computing

In [1]:
import numpy as np # recommended import conventions
a = np.array([0,1,2,3])
a

array([0, 1, 2, 3])

## Why is NumPy useful?

It is a memory-efficient container that provides fast numerical operations.

In [9]:
L = range(1000)
%timeit [i**2 for i in L]

print("\n------------------------------------\n")

a = np.arange(1000)
%timeit a**2

345 µs ± 17.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

------------------------------------

1.55 µs ± 43.8 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


## Interactive Help

In [6]:
np.array?

In [7]:
np.lookfor("create array")

Search results for 'create array'
---------------------------------
numpy.array
    Create an array.
numpy.memmap
    Create a memory-map to an array stored in a *binary* file on disk.
numpy.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.fromiter
    Create a new 1-dimensional array from an iterable object.
numpy.partition
    Return a partitioned copy of an array.
numpy.ctypeslib.as_array
    Create a numpy array from a ctypes array or POINTER.
numpy.ma.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.ma.make_mask
    Create a boolean mask from an array.
numpy.ctypeslib.as_ctypes
    Create and return a ctypes object from a numpy array.  Actually
numpy.ma.mrecords.fromarrays
    Creates a mrecarray from a (flat) list of masked arrays.
numpy.ma.mvoid.__new__
    Create a new masked array from scratch.
numpy.lib.format.open_memmap
    Open a .npy file as a memory-mapped array.
numpy.ma.MaskedArray.__new_

In [8]:
np.con*?

## Import conventions

In [ ]:
import numpy as np

## Creating arrays

### Manual construction of arrays

### 1-D:

In [ ]:
a = np.array([0, 1, 2, 3])
a

In [ ]:
a.ndim

In [ ]:
a.shape

In [ ]:
len(a)

### 2-D, 3-D:

In [ ]:
b = np.array([[0, 1, 2], [3, 4, 5]])
b

In [ ]:
b.ndim

In [ ]:
b.shape

In [ ]:
len(b)

In [ ]:
c = np.array([[[1], [2]], [[3], [4]]])
c

In [ ]:
c. shape

## Exercise

* Create a simple two dimensional array. First, redo the examples from above. And then create your own: how about odd numbers counting backwards on the first row, and even numbers on the second?

* Use the functions len(), numpy.shape() on these arrays. How do they relate to each other? And to the ndim attribute of the arrays?

## Functions for creating arrays

In practice, we rarely enter the items one by one.

### Create evenly spaced arrays:

In [ ]:
a = np.arange(10) # 0 .. n-1
a

In [ ]:
b = np.arange(1, 9, 2) # start, end (exclusive), step
b

### Create array by specifying number of points:

In [2]:
c = np.linspace(0, 1, 6)   # start, end, num-points
c

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [ ]:
d = np.linspace(0, 1, 5, endpoint=False)
d

### Some common arrays:

In [7]:
a = np.ones((3, 3))  # reminder: (3, 3) is a tuple
print(a)
print("\n")
b = np.zeros((2, 2))
print(b)
print("\n")
c = np.eye(3)
print(c)
print("\n")
d = np.diag(np.array([1, 2, 3, 4]))
print(d)
print("\n")

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


[[0. 0.]
 [0. 0.]]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]




### Random numbers

In [8]:
a = np.random.rand(4)       # uniform in [0, 1]
a

array([0.35821125, 0.42762129, 0.97356289, 0.34076967])

In [9]:
b = np.random.randn(4)      # Gaussian
b 

array([0.27423773, 0.12342252, 0.54674491, 1.12422082])

In [ ]:
np.random.seed(1234)        # Setting the random seed

## Exercise

* Experiment with `arange`, `linspace`, `ones`, `zeros`, `eye` and `diag`.

* Create different kinds of arrays with random numbers.

* Try setting the seed before creating an array with random values.

* Look at the function `np.empty`. What does it do? When might this be useful?

## Basic Data Types

You might sometimes notice that, in some instances, array elements are displayed with a trailing dot (e.g. 2. vs 2). This is due to a difference in the data-type used:

In [ ]:
a = np.array([1, 2, 3])
a.dtype

In [ ]:
b = np.array([1., 2., 3.])
b.dtype

Different data-types allow us to store data more compactly in memory, but most of the time we simply work with floating point numbers. Note that, in the example above, NumPy auto-detects the data-type from the input.

You can explicitly specify which data-type you want:

In [ ]:
c = np.array([1, 2, 3], dtype=float)
c.dtype

The **default** data type is floating point:

In [ ]:
a = np.ones((3, 3))
a.dtype

## Other Data Types

### Complex:

In [ ]:
d = np.array([1+2j, 3+4j, 5+6*1j])
d.dtype

### Bool:

In [ ]:
e = np.array([True, False, False, True])
e.dtype

### Strings:

In [ ]:
f = np.array(['Bonjour', 'Hello', 'Hallo'])
f.dtype     # <--- strings containing max. 7 letters  

### Others:

* int32
* int64
* uint32
* uint64

## Basic visualization

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt

In [ ]:
x = np.linspace(0, 3, 20)
y = np.linspace(0, 9, 20)
plt.plot(x, y)       # line plot      

In [ ]:
plt.plot(x, y, 'o')  # dot plot  

### Plotting 2D arrays

In [ ]:
image = np.random.rand(30, 30)
plt.imshow(image, cmap=plt.cm.hot)    

plt.colorbar()   

### Exercise: Simple visualizations

* Plot some simple arrays: a cosine as a function of time and a 2D matrix.

* Try using the `gray` colormap on the 2D matrix.

## Indexing and slicing

The items of an array can be accessed and assigned to the same way as other Python sequences (e.g. lists):

In [ ]:
a = np.arange(10)
a

In [ ]:

a[0], a[2], a[-1]

The usual python idiom for reversing a sequence is supported:

In [ ]:
a[::-1]

For multidimensional arrays, indexes are tuples of integers:

In [ ]:
a = np.diag(np.arange(3))
a

In [ ]:
a[1, 1]

In [ ]:
a[2, 1] = 10 # third line, second column
a

In [ ]:
a[1]

** Note: **
* In 2D, the first dimension corresponds to rows, the second to columns.
* for multidimensional a, `a[0]` is interpreted by taking all elements in the unspecified dimensions.

**Slicing:** Arrays, like other Python sequences can also be sliced:

In [ ]:
a = np.arange(10)
a

In [ ]:
a[2:9:3] # [start:end:step]

In [ ]:
a[:4]

In [ ]:
a[1:3]

a[::2]

a[3:]

An illustrated summary of NumPy indexing and slicing:

<img src="Files/numpy_indexing.png">

You can also combine assignment and slicing:

In [ ]:
a = np.arange(10)
a[5:] = 10
a

In [ ]:
b = np.arange(5)
a[5:] = b[::-1]
a

## Exercise: Indexing and Slicing

* Try the different flavours of slicing, using `start`, `end` and `step`: starting from a linspace, try to obtain odd numbers counting backwards, and even numbers counting forwards.

* Reproduce the slices in the diagram above. You may use the following expression to create the array:

In [ ]:
np.arange(6) + np.arange(0, 51, 10)[:, np.newaxis]

### Exercise: Array creation

Create the following arrays(with correct data types):

Hint: np.diag?

### Exercise: Tiling for array creation

Skim through the documentation for `np.tile`, and use this function to construct the array:

## Copies and views

A slicing operation creates a view on the original array, which is just a way of accessing array data. Thus the original array is not copied in memory. You can use `np.may_share_memory()` to check if two arrays share the same memory block. Note however, that this uses heuristics and may give you false positives.

In [ ]:
a = np.arange(10)
a

In [ ]:
b = a[::2]
b

In [ ]:
np.may_share_memory(a, b)

In [ ]:
b[0] = 12
b

In [ ]:
a

In [ ]:
a = np.arange(10)
c = a[::2].copy()  # force a copy
c[0] = 12
a

In [ ]:
np.may_share_memory(a, c)

This behavior can be surprising at first sight… but it allows to save both memory and time.

## Worked example: Prime number sieve

<img src="Files/prime_number_sieve.png">

Compute prime numbers in 0–99, with a sieve

* Construct a shape (100,) boolean array `is_prime`, filled with True in the beginning:

In [ ]:
is_prime = np.ones((100,), dtype=bool)

* Cross out 0 and 1 which are not primes:

In [ ]:
is_prime[:2] = 0

* For each integer `j` starting from 2, cross out its higher multiples:

In [ ]:
N_max = int(np.sqrt(len(is_prime) - 1))
for j in range(2, N_max + 1):
    is_prime[2*j::j] = False

* Skim through `help(np.nonzero)`, and print the prime numbers

* Follow-up:

    * Move the above code into a script file named `prime_sieve.py`
    * Run it to check it works
    * Use the optimization suggested in the `sieve of Eratosthenes`:
        1. Skip j which are already known to not be primes
        2. The first number to cross out is `j^2`

# Fancy indexing

NumPy arrays can be indexed with slices, but also with boolean or integer arrays (**masks**). This method is called *fancy indexing*. It creates **copies not views**.

### Using boolean masks

In [ ]:
np.random.seed(3)
a = np.random.randint(0, 21, 15)
print(a)

(a % 3 == 0)


mask = (a % 3 == 0)
extract_from_a = a[mask] # or,  a[a%3==0]
extract_from_a           # extract a sub-array with the mask



Indexing with a mask can be very useful to assign a new value to a sub-array:

In [ ]:
a[a % 3 == 0] = -1
a

### Indexing with an array of integers

In [ ]:
a = np.arange(0, 100, 10)
a

Indexing can be done with an array of integers, where the same index is repeated several time:

In [ ]:
a[[2, 3, 2, 4, 2]]  # note: [2, 3, 2, 4, 2] is a Python list

New values can be assigned with this kind of indexing:

In [ ]:
a[[9, 7]] = -100
a

When a new array is created by indexing with an array of integers, the new array has the same shape as the array of integers:

In [ ]:
a = np.arange(10)
idx = np.array([[3, 4], [9, 7]])
idx.shape

a[idx]

<img src="Files/numpy_fancy_indexing.png">

## Exercise: Fancy indexing

* Again, reproduce the fancy indexing shown in the diagram above.

* Use fancy indexing on the left and array creation on the right to assign values into an array, for instance by setting parts of the array in the diagram above to zero.

# Numerical operations on arrays

## Elementwise operations

### Basic operations

With scalars:

In [ ]:
a = np.array([1, 2, 3, 4])

print(a + 1)

print(2**a)

All arithmetic operates elementwise:

In [ ]:
b = np.ones(4) + 1
a - b

a * b


j = np.arange(5)
2**(j + 1) - j


These operations are of course much faster than if you did them in pure python:

In [ ]:
a = np.arange(10000)
%timeit a + 1  

l = range(10000)
%timeit [i+1 for i in l] 

### Array multiplication is not matrix multiplication:

In [ ]:
c = np.ones((3, 3))
c * c                   # NOT matrix multiplication!


**Note: Matrix multiplication:**

In [ ]:
c.dot(c)

## Exercise: Elementwise operations

* Try simple arithmetic elementwise operations: add even elements with odd elements
* Time them against their pure python counterparts using `%timeit`.
* Generate:
    * `[2**0, 2**1, 2**2, 2**3, 2**4]`
    * `a_j = 2^(3*j) - j`

## Other operations

**Comparisons:**

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])

print(a == b)

print(a > b)

Array-wise comparisons:

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([1, 2, 3, 4])

print(np.array_equal(a, b))

print(np.array_equal(a, c))

**Logical operations:**

In [ ]:
a = np.array([1, 1, 0, 0], dtype=bool)
b = np.array([1, 0, 1, 0], dtype=bool)

print(np.logical_or(a, b))

print(np.logical_and(a, b))

**Transcendental functions:**

In [ ]:
a = np.arange(1,5)

print(np.sin(a))

print(np.log(a))

print(np.exp(a))

**Shape mismatches**

In [ ]:
a = np.arange(4)
a + np.array([1, 2])  

**Transposition:**

In [ ]:
a = np.triu(np.ones((3, 3)), 1)   # see help(np.triu)
print(a)

print("\n")

print(a.T)

**Note: The transposition is a view**

As a result, the following code is **wrong**, and will **not make a matrix symmetric:**

In [ ]:
a += a.T

It will work for small arrays (because of buffering) but fail for large one, in unpredictable ways.

**Note: Linear algebra**

The sub-module **numpy.linalg** implements basic linear algebra, such as solving linear systems, singular value decomposition, etc. 

However, use of **scipy.linalg** is recommended.

### Exercise: Other operations

* Look at the help for `np.allclose`. When might this be useful?
* Look at the help for `np.triu` and `np.tril`.

# Basic reductions

## Computing sums

In [ ]:
x = np.array([1, 2, 3, 4])

print(np.sum(x))

print(x.sum())

### Sum by rows and by columns:

In [ ]:
x = np.array([[1, 1], [2, 2]])
x

In [ ]:
x.sum(axis=0)   # columns (first dimension)

In [ ]:
x[:, 0].sum(), x[:, 1].sum()

In [ ]:
x.sum(axis=1)   # rows (second dimension)

In [ ]:
x[0, :].sum(), x[1, :].sum()

Same idea in higher dimensions:

In [ ]:
x = np.random.rand(2, 2, 2)
x.sum(axis=2)[0, 1]     

x[0, 1, :].sum()  

### Other reductions

**Extrema:**

In [ ]:
x = np.array([1, 3, 2])

print(x.min())
print(x.max())

print("\n")

print(x.argmin())  # index of minimum
print(x.argmax())  # index of maximum


**Logical operations:**

In [ ]:
print (np.all([True, True, False]))

np.any([True, True, False])

**Note:** Can be used for array comparisons:

In [ ]:
a = np.zeros((100, 100))
np.any(a != 0)

np.all(a == a)


a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])
((a <= b) & (b <= c)).all()

### Statistics:

In [ ]:
x = np.array([1, 2, 3, 1])
y = np.array([[1, 2, 3], [5, 6, 1]])
x.mean()

np.median(x)

np.median(y, axis=-1) # last axis


x.std()          # full population standard dev.

## Exercise: Reductions

* What is the difference between `sum` and `cumsum`?

### Worked example: Data statistics

Data in populations.txt describes the populations of hares and lynxes (and carrots) in northern Canada during 20 years.

First view the data:

In [ ]:
!cat data/populations.txt

Now, load the data into a NumPy array:

In [ ]:
data = np.loadtxt('data/populations.txt')
year, hares, lynxes, carrots = data.T  # trick: columns to variables

Then, plot it:

In [ ]:
% matplotlib inline
from matplotlib import pyplot as plt
plt.axes([0.2, 0.1, 0.5, 0.8]) 
plt.plot(year, hares, year, lynxes, year, carrots) 
plt.legend(('Hare', 'Lynx', 'Carrot'), loc=(1.05, 0.5)) 

The mean populations over time:

In [ ]:
populations = data[:, 1:]
populations.mean(axis=0)

The sample standard deviations:

In [ ]:
populations.std(axis=0)

Which species has the highest population each year?:

In [ ]:
np.argmax(populations, axis=1)


## Worked Example: diffusion using a random walk algorithm

<img src="Files/random_walk.png">

Let us consider a simple 1D random walk process: at each time step a walker jumps right or left with equal probability.

We are interested in finding the typical distance from the origin of a random walker after `t` left or right jumps? 

We are going to simulate many “walkers” to find this law, and we are going to do so using array computing tricks: we are going to create a 2D array with the “stories” (each walker has a story) in one direction, and the time in the other:

<img src="Files/random_walk_schema.png">

In [ ]:
n_stories = 1000 # number of walkers
t_max = 200      # time during which we follow the walker

We randomly choose all the steps 1 or -1 of the walk:

In [ ]:
t = np.arange(t_max)
steps = 2 * np.random.randint(0, 1 + 1, (n_stories, t_max)) - 1 # +1 because the high value is exclusive
np.unique(steps) # Verification: all steps are 1 or -1

We build the walks by summing steps along the time:

In [ ]:
positions = np.cumsum(steps, axis=1) # axis = 1: dimension of time
sq_distance = positions**2

We get the mean in the axis of the stories:

In [ ]:
mean_sq_distance = np.mean(sq_distance, axis=0)

Plot the results:

In [ ]:
plt.figure(figsize=(4, 3)) 

plt.plot(t, np.sqrt(mean_sq_distance), 'g.', t, np.sqrt(t), 'y-') 

plt.xlabel(r"$t$") 

plt.ylabel(r"$\sqrt{\langle (\delta x)^2 \rangle}$") 

plt.tight_layout() # provide sufficient space for labels

We find a well-known result in physics: the RMS distance grows as the square root of the time!

# Broadcasting

* Basic operations on `numpy` arrays (addition, etc.) are elementwise

* This works on arrays of the same size.

    Nevertheless, It’s also possible to do operations on arrays of different sizes if *NumPy* can transform these arrays so that they all have the same size: this conversion is called **broadcasting**
    .

The image below gives an example of broadcasting:

<img src="Files/numpy_broadcasting.png">

Let's verify:

In [ ]:
a = np.tile(np.arange(0, 40, 10), (3, 1)).T
print(a)

print("\n")

b = np.array([0, 1, 2])
print(a + b)

We have already used broadcasting without knowing it!:

In [ ]:
a = np.ones((4, 5))
a[0] = 2  # we assign an array of dimension 0 to an array of dimension 1
a


A useful trick:

In [ ]:
a = np.arange(0, 40, 10)
print(a.shape)
print("\n")

a = a[:, np.newaxis]  # adds a new axis -> 2D array
print(a.shape)
print("\n")
print(a)
print("\n")
print(a + b)

Broadcasting seems a bit magical, but it is actually quite natural to use it when we want to solve a problem whose output data is an array with more dimensions than input data.


## Worked Example: Broadcasting

Let’s construct an array of distances (in miles) between cities of Route 66: Chicago, Springfield, Saint-Louis, Tulsa, Oklahoma City, Amarillo, Santa Fe, Albuquerque, Flagstaff and Los Angeles.

<img src="Files/route66.png">

In [ ]:
mileposts = np.array([0, 198, 303, 736, 871, 1175, 1475, 1544,
       1913, 2448])
distance_array = np.abs(mileposts - mileposts[:, np.newaxis])
distance_array

A lot of grid-based or network-based problems can also use broadcasting. For instance, if we want to compute the distance from the origin of points on a 10x10 grid, we can do

In [ ]:
x, y = np.arange(5), np.arange(5)[:, np.newaxis]
distance = np.sqrt(x ** 2 + y ** 2)
distance

Or in color:

In [ ]:
plt.pcolor(distance)    
plt.colorbar()    

**Remark** : the **numpy.ogrid()** function allows to directly create vectors **x** and **y** of the previous example, with two “significant dimensions”:

In [ ]:
x, y = np.ogrid[0:5, 0:5]
x, y

In [ ]:
x.shape, y.shape

In [ ]:
distance = np.sqrt(x ** 2 + y ** 2)

So, `np.ogrid` is very useful as soon as we have to handle computations on a grid. On the other hand, `np.mgrid` directly provides matrices full of indices for cases where we can’t (or don’t want to) benefit from broadcasting:

In [ ]:
x, y = np.mgrid[0:4, 0:4]
x

In [ ]:
y

## Array shape manipulation

## Flattening

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.ravel())
print("\n")
print(a)
a.T

In [ ]:
a.T.ravel()

**Note:** In higher dimensions: last dimensions ravel out "first".

## Reshaping

The inverse operation to flattening:

In [ ]:
a.shape

In [ ]:
b = a.ravel()
print(b)
b = b.reshape((2, 3))
b

In [ ]:
a.reshape((2, -1))    # unspecified (-1) value is inferred

**Note:** `ndarray.reshape` may return a view (cf `help(np.reshape)`)), or copy

In [ ]:
b[0, 0] = 99
a

**Beware:** reshape may also return a copy!

In [ ]:
a = np.zeros((3, 2))
b = a.T.reshape(3*2)
b[0] = 9
a

To understand this you need to learn more about the memory layout of a numpy array.

# Adding a dimension

Indexing with the `np.newaxis` object allows us to add an axis to an array (you have seen this already above in the broadcasting section):

In [ ]:
z = np.array([1, 2, 3])
z

In [ ]:
z[:, np.newaxis]

In [ ]:
z[np.newaxis, :]

# Dimension shuffling

In [ ]:
a = np.arange(4*3*2).reshape(4, 3, 2)
a.shape

In [ ]:
a[0, 2, 1]

In [ ]:
b = a.transpose(1, 2, 0)
b.shape

In [ ]:
b[2, 1, 0]

Also creates a view:

In [ ]:
b[2, 1, 0] = -1
a[0, 2, 1]

### Resizing

Size of an array can be changed with `ndarray.resize`:

In [ ]:
a = np.arange(4)
a.resize((8,))
a

However, it must not be referred to somewhere else:

In [ ]:
b = a
a.resize((4,))

## Exercise: Shape manipulations

* Look at the docstring for `reshape`, especially the notes section which has some more information about copies and views.

* Use `flatten` as an alternative to `ravel`. What is the difference? (Hint: check which one returns a view and which a copy)

* Experiment with `transpose` for dimension shuffling.

# Sorting data

Sorting along an axis:

In [ ]:
a = np.array([[4, 3, 5], [1, 2, 1]])
b = np.sort(a, axis=1)
b

**Note:** Sorts each row separately!

In-place sort:

In [ ]:
a.sort(axis=1)
a

Sorting with fancy indexing:

In [ ]:
a = np.array([4, 3, 1, 2])
j = np.argsort(a)
j

In [ ]:
a[j]

Finding minima and maxima:

In [ ]:
a = np.array([4, 3, 1, 2])
j_max = np.argmax(a)
j_min = np.argmin(a)
j_max, j_min

# Exercise: Sorting

* Try both in-place and out-of-place sorting.

* Try creating arrays with different dtypes and sorting them.

* Use `all` or `array_equal` to check the results.

* Look at `np.random.shuffle` for a way to create sortable input quicker.

* Combine `ravel`, `sort` and `reshape`.

* Look at the `axis` keyword for `sort` and rewrite the previous exercise.

# Summary

### What do you need to know to get started?

* Know how to create arrays : `array`, `arange`, `ones`, `zeros`.

* Know the shape of the array with `array.shape`, then use slicing to obtain different views of the array: `array[::2]`, etc. Adjust the shape of the array using `reshape` or flatten it with `ravel`.

* Obtain a subset of the elements of an array and/or modify their values with masks

In [ ]:
a[a < 0] = 0
a

* Know miscellaneous operations on arrays, such as finding the mean or max (`array.max()`, `array.mean()`). No need to retain everything, but have the reflex to search in the documentation (online docs, `help()`, `lookfor()`)!!

* For advanced use: master the indexing with arrays of integers, as well as broadcasting. Know more NumPy functions to handle various array operations.



# More elaborate arrays

## More data types

### Casting

“Bigger” type wins in mixed-type operations:

In [ ]:
np.array([1, 2, 3]) + 1.5

Assignment never changes the type!

In [ ]:
a = np.array([1, 2, 3])
a.dtype

In [ ]:
a[0] = 1.9     # <-- float is truncated to integer
a

Forced casts:

In [ ]:
a = np.array([1.7, 1.2, 1.6])
b = a.astype(int)  # <-- truncates to integer
b

Rounding:

In [ ]:
a = np.array([1.2, 1.5, 1.6, 2.5, 3.5, 4.5])
b = np.around(a)
b                    # still floating-point

In [ ]:
c = np.around(a).astype(int)
c

http://www.scipy-lectures.org/intro/numpy/elaborate_arrays.html